### ISSUE TITLE
Relation to other projects (tsify, tsync, etc.)

### ISSUE THREAD

**Issue by siefkenj** [DmitryAstafyev/tslink#1]
This looks like a really exciting project! It also looks rather new. Does it have any relation to other typescript binding projects like `tsify` or `tsync`? Is it solving a different problem than those libraries?

**Comment by DmitryAstafyev** [comment]
@siefkenj thanks for the question. Tslink is a standalone crate, which was created with a focus on TS on NodeJs and usage with such kind of crates like node-bindgen. It's pretty much like crates, which you've highlighted and indeed has the same goal at the end - reflect rust-code in JavaScript world. 

But not only reflecting of code is a goal of tslink. Tslink also helps to create npm package with necessary descriptions and types. 

For example, using tslink + node-bindgen you can get npm-package with node module based on rust, which can be used as npm dependency.

**Comment by DmitryAstafyev** [comment]
@siefkenj if we go into details, I would highlight next points:
- tslink cares also about return-types from method and functions. It allows to use  primitive types indeed and complex too. To avoid  restrictions of crates, which generates modules (node or wasm) tslink supports converting to JSON based on serde standards.
- tslink supports async functions/methods as well and represent it as promises on TS side.
- tslink generates also JS wrappers to handle possible type-errors  . So this is not only TS, it's also about JavaScript. 
- if we are talking about node-bindgen crate, tslink helps not only with TS, but also helps organize public API on node-bindgen side, because allows you get rid of JsValue converting using JSON instead. But remember, JSON converting is not always a good solution, in some cases would be better to convert stuff into JsValue, it depends on context and goals.
- and, as I've said tsling generates js files for npm package and cares about loading of node module out of box.

If you don't mind, I would close issue )

**Comment by siefkenj** [comment]
Thanks for these answers! Would you mind putting some of this information in the README (or even a comparison table?)?

**Comment by DmitryAstafyev** [comment]
In general if should work with `wasm-bindgen`, but always better to have tests, examples etc. 
Created: #3

**Comment by icsmw** [comment]
@siefkenj take in account... `tslink` moved to new repository

**Comment by icsmw** [comment]
@siefkenj  about `wasm-bindgen` can you give me your vision (or wishes), which kind of feature you would like to see from `tslink`. Asking because `wasm-bindgen` generates `.d.ts` files as well. Probably not for `JsValue` indeed, but it has already basic support of it.

**Comment by siefkenj** [comment]
I would like to be able to use automatically generated bindings from wasm modules with typescript and have serialization happen transparently (tsify can mostly do this, but it had some errors with the generated types). `wasm-bindgen` can automatically convert to `JsValue`, but the type in the exported `.d.ts` file is `any`, rather than the structure of the object created.
